### ISSUE TITLE
Integration Tests fail due to ParameterResolutionException

### ISSUE THREAD

**Issue by offa** [jhnc-oss/jenkins-pool-node-config#41]
Integration Tests fail due to `ParameterResolutionException`:

```
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.jvnet.hudson.test.JenkinsRule r] in method [void io.jhnc.jenkins.plugins.poolnodes.PoolConfigurationIT.entryIsSavedAcrossConfigurations(java.lang.String,org.jvnet.hudson.test.JenkinsRule) throws java.lang.Exception]: java.nio.file.NoSuchFileException: […]/jenkins-pool-node-config/target/tmp/jenkins15472323168016129736
[…]
    Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.hudson.test.TestPluginManager
        at org.jvnet.hudson.test.JenkinsRule.<init>(JenkinsRule.java:352)
        at io.jhnc.jenkins.plugins.test.JUnit5JenkinsRule.<init>(JUnit5JenkinsRule.java:42)
        at io.jhnc.jenkins.plugins.test.JenkinsExtension.lambda$resolveParameter$0(JenkinsExtension.java:62)
[…]
Caused by: java.lang.Error: java.nio.file.NoSuchFileException: […]/jenkins-pool-node-config/target/tmp/jenkins15472323168016129736
    at org.jvnet.hudson.test.TestPluginManager.<clinit>(TestPluginManager.java:46)
    at org.jvnet.hudson.test.JenkinsRule.<init>(JenkinsRule.java:352)
    at io.jhnc.jenkins.plugins.test.JUnit5JenkinsRule.<init>(JUnit5JenkinsRule.java:42)
    at io.jhnc.jenkins.plugins.test.JenkinsExtension.lambda$resolveParameter$0(JenkinsExtension.java:62)
[…]

**Comment by offa** [comment]
Execution through `verify` goal works.
